### ISSUE TITLE
Reimplement on swift-nio-http-client

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/SwiftyRequest#58]
Now that https://github.com/swift-server/swift-nio-http-client has been released, we should experiment with re-plumbing this package so that it uses `swift-nio-http-client` for transport instead of `URLSession`.

**Comment by saiHemak** [comment]
Basically ```RestRequest ```  dealts with HTTP requests in ```SwiftyRequest ``` and uses ```URLSession``` of foundation . So , the goal of this workitem is to re-factoring the code to use   ```swift-nio-http-client```  instead of ```URLSession```.

**Comment by Andrew-Lees11** [comment]
A prototype of SwfityRequest using the renamed [async-http-client](https://github.com/swift-server/async-http-client) has been developed on the [issue.nio](https://github.com/IBM-Swift/SwiftyRequest/tree/issue.nio) branch. 
This branch no longer depends on `URLSession` and uses the nio client instead. 
This would be a breaking change since it is only supported on Swift 5.

The following changes to API have also happened:
- `RestError.swift` has been added as an extensible struct
- All JSON code has been removed and replaced with `Codable`
- `HTTPMethod.swift` has been removed and replaced with the [NIOHTTP1 HTTPMethod](https://apple.github.io/swift-nio/docs/current/NIOHTTP1/Enums/HTTPMethod.html)
- headerParameters has changed from a [String:String] to `HTTPHeaders` 
- response() now returns `Result<HTTPClient.Response, Error>` instead of `(Data?, HTTPURLResponse?, Error?)`
- RestResponse now represents an HTTPClient.Response that is generic over the body instead of an HTTPURLResponse with the result of the body. 
- `Credentials` input has been converted to be an extensible struct
- `RestRequest` initializer now throws in the case of an invalid URL
- Client Credentials have been removed since they were not working anyway.

The tests have been updated for the new API. They Pass on MacOS but the project is currently failing to compile on Linux.

The RestRequest pattern of stating the type you expect when you make the request is a bit strange. Before we release this it might be worth looking into having a single RestRequest.response() but have helper functions on the body for decoding to the expected type.

**Comment by ianpartridge** [comment]
Update: Andy fixed the compilation on Linux, so there's nothing blocking this.

**Comment by ianpartridge** [comment]
> Client Credentials have been removed since they were not working anyway.

This could be fixed by passing in a NIO `TLSConfiguration`.

**Comment by djones6** [comment]
Support for client credentials was requested in #57, so we should definitely consider implementing it as part of this rework.

**Comment by djones6** [comment]
The current prototype no longer compiles because of https://github.com/swift-server/async-http-client/commit/e64448e1eff26022040ca587c0e637a05e82aa7d (HTTPClient.Request properties are now let constants).  It'll need some rework as it's no longer a direct translation of what we did with URLSession.
